### ISSUE TITLE
Email as another attribute in response

### ISSUE THREAD

**Issue by uditnarayan** [einfallstoll/express-ntlm#14]
Hi

I have a situation where I also need the email of the user who is being authenticated from ldap server. The current response i get only contains 
`{
    "DomainName":"MYDOMAIN",
    "UserName":"MYUSER",
    "Workstation":"MYWORKSTATION"
}`

It would be good if there is any way of getting email of the person because in my scenerio multiple email addresses are mapped to same user account 
eg.
The actual email account is say: 
abc@xyz.com

As our company has a subsidiary, therefore some people has multiple email ids like this
abc@xyz.com (Original)
abc@subsidry.com (if abc is an employee in subsidary)

Both these email addresses points to same email account. Therefore, we need to know the email of the person as well.

**Comment by einfallstoll** [comment]
The NTLM Protocol doesn't provide the E-Mail Address, which makes sense, because it's not really associated with the current user logged in on a workstation.

If you need this functionality just write a simple middleware that uses an ActiveDirecrory module from
NPM and queries against it using the current username of the user logged in. I've done this several times in the past and it worked very well.

**Comment by danbopes** [comment]
@einfallstoll Would you be able to provide an example or some more direction? I'm currently trying to do this, but I'm finding that all the libraries out there only allow simple bind, which requires the password in raw text in order to search the active directory tree. I was not able to query a user without first authenticating to the domain controller first.

**Comment by einfallstoll** [comment]
I want to share some thoughts about this: I don't like the idea of `express-ntlm` providing more information than what is already included (which is part of the NTLM specification by Microsoft). But I *do like* the idea of using the already set up authentication to the Active Directory to read more data about the user, instead of using a read-only service account, that has to be included in the source code (as you mentioned using a raw password). Although it should be no problem to store a read-only AD service account in the source code like you have to do for any other database user you probably are using.

*Please note: I didn't develop this module from scratch. It's a port from a Python library for Apache httpd. Therefore a lot of things this module does is magic.*

`express-ntlm` acts as a proxy between the client of a user and the Active Directory. It authenticates the client against the Active Directory by wrapping the clients request for the Active Directory and unwraps the response of the Active Directory for the client. As soon as there is a success message this module just abandons everything and marks the connection as 'successfully authenticated' 

On [this line](https://github.com/einfallstoll/express-ntlm/blob/1b6d50b76074a12a0bbbcfce0e220d881458067d/lib/express-ntlm.js#L170) I receive a result which appears to be some [SASL credentials](https://github.com/einfallstoll/express-ntlm/blob/1b6d50b76074a12a0bbbcfce0e220d881458067d/lib/NTLM_AD_Proxy.js#L68) that might be used for a SASL bind. But this is where my know-how stops.

My suggestion: Have a look at the mentioned line and wether it *really* provides SASL credentials. You can inspect this by a simple `console.log(result)` to see what it includes. Then try to find an Active Directory client that provides some sort of SASL bind mechanism. I'd be more than happy to give you access to the SASL credentials through this module if you can do something useful with them, as long as you share some code snippets to be included in the README for other users.
