### ISSUE TITLE
Chrome getting 401 Unauthorized responses if not accessing page directly

### ISSUE THREAD

**Issue by nmstoker** [einfallstoll/express-ntlm#18]
I've seen issue #16 and I get something similar, but I wonder if the problem might not to be with Chrome, because it works correctly to do authentication against NTLM (and checking various group info from the domain controller) if I access the URL directly, eg to test the API response I open it in the browser with the URL. It is only if I do a GET of that URL from within my AngularJS app that I get the "No Authorisation header" response.

I'm testing in Chrome 49.0.2 (our IT department keep us back from using the latest version :disappointed: )

The headers, NTLM and such aren't my area of expertise, so maybe I'm overlooking something but is there anywhere you'd suggest I start looking to get to the bottom of this?

**Comment by einfallstoll** [comment]
I'd suggest to use the middleware without any parameters (e.g. `app.use(ntlm())`) this will disable the authentication and allows to use any username/password-combination.

If it works that way, there might be a problem with the active directory, since this module just works as a proxy and just does some translations between browser and active directory.

If it doesn't work try to use Internet Explorer (_did I really said that?_) to see wether it's a problem with chrome or that specific version.

I even used this module with socket.io and Ajax and there wasn't any issue with NTLM.

**Comment by nmstoker** [comment]
Will give that a go. Thanks for this - it reassures me to hear you've used it in the way I wanted w/o problems.

**Comment by nmstoker** [comment]
This wasn't a problem with express-ntlm, but thank you for the suggestions and the mention you'd managed something similar (which spurred me on!).  Definitely fine to close this as a non-issue.

In case it's useful for anyone stumbling on this in a similar situation: I worked out that I needed to make some changes on the server side and in my AngularJS code, largely in line with what's reported here for the Access-Control-Allow-Credentials and withCredentials parts (beyond the CORS settings I had in place already): https://gist.github.com/mlynch/be92735ce4c547bd45f6
