### ISSUE TITLE
express-ntlm authentication fails to run when behind nginx reverse proxy

### ISSUE THREAD

**Issue by stefanheine** [einfallstoll/express-ntlm#20]
Hi,

I have a module using express-ntlm authentication and it's working perfectly standalone.

but when I expose that module through nginx, it fails in:
TypeError: Cannot read property 'authenticate' of null
   at handle_type3 (/app/node_modules/express-ntlm/lib/express-ntlm.js:169:14)
   at Authentication.ntlmMiddleware (/app/node_modules/express-ntlm/lib/express-ntlm.js:245:24)

it seems like the nginx forwarding somehow breaks the proper communication to the NTLM DC.

do you have any idea if there is a solution?

Regards
  Stefan

**Comment by einfallstoll** [comment]
NTLM is designed for corporate networks without a proxy between the client and the application. It does authorise the TCP connection instead of the HTTP session and with a proxy between, it'll authorise the connection between the proxy and the application and therefore mixing up users if the proxy shares the same connection or "forgetting" users if the proxy suddenly uses a different connection for the same user. The latter leads to the mentioned error if it happens during the negotiation between client and application.

In an early state of this module `express-ntlm` tried to create a session during the negotiation, which failed (see 50d9ac4a06552ab39d49eadf9efe68f02d122176) even though [RFC6265](https://tools.ietf.org/html/rfc6265#section-3) makes it clear it MUST be possible: "User agents [...] MUST process Set-Cookie headers contained in other responses (including responses with 400- and 500-level status codes)."

A possible solution to this problem might be to set the `keep-alive` property in nginx as mentioned in an [answer from StackOverflow regarding this issue](http://stackoverflow.com/a/22918442/377369) but it could end in the "multiple-users same-connection"-problem mentioned earlier (see [here](http://stackoverflow.com/a/22806907/377369)).

Another option would be to abandon the proxy completely and connect directly to the application on port 80 or build a custom reverse proxy that authenticates the user, creates a session and keeps the session data on a shared store, that is accessible by all applications behind the proxy (e.g. [expressjs/session](https://github.com/expressjs/session) in combination with [visionmedia/connect-redis](http://github.com/visionmedia/connect-redis).

**Comment by stefanheine** [comment]
thanks for these references. this helped me to get the NTLM running together with nginx.

**Comment by einfallstoll** [comment]
Could you provide sample code, so I can include it in the readme?

**Comment by stefanheine** [comment]
I realized that it's not possible. It works ok in a simple test env:

```
upstream http_backend {
    server 1.1.1.1:80;
    keepalive 16;
}

server {
...
location / {
       proxy_pass http://http_backend/;
       proxy_http_version 1.1;
       proxy_set_header Connection "";
    ...
    }
 }
```

**but as soon as it's rolled out to multiple users, it's broken.**

there is a pretty good explanation available at [ruby forum](https://www.ruby-forum.com/topic/207616)
also describing that there is a commercial version of nginx offering the proper support.

in short:

> By using common keepalive pool as in the configuration
> above any authentication will basically authenticate arbitrary
> clients who happen to use the authenticated connection from the
> cache of keepalive connections to upstream servers.

> Proper support for Windows Authentication (aka NTLM) requires
> connections to backend servers to be bound to particular
> connections to clients, as NTLM authenticates connections, not
> requests.  
> Proper support for proxying NTLM authentication was recently
> implemented in our commercial version, see
> http://nginx.org/r/ntlm

**Comment by einfallstoll** [comment]
nginx plus is prized at $1.900 per instance per year. That's a lot for NTLM... implementing a custom solutions is likely cheaper.
