### ISSUE TITLE
Provide Typings for TypeScript

### ISSUE THREAD

**Issue by weber-d** [einfallstoll/express-ntlm#53]
Typings are required for usage in TypeScript. So we don't need fallback to JavaScript, which is not a good practive in TS. I already declared the required Typings, so that you simply can add them in a `.d.ts` file like this:

```ts
import express = require('express')

export interface NtlmRequest extends express.Request {
     ntlm?: NtlmInfo
}
export interface NtlmInfo {
    DomainName: string 
    UserName: string
    Workstation: string
    push?:void
}
```

Example usage:

```ts
import { NtlmRequest } from './express-ntlm';

app.all('*', (request:NtlmRequest, response:Response) => {
    if(request.ntlm == undefined){
        return
    }
    console.log(request.ntlm.UserName)
    response.end(request.ntlm.UserName)
});
```

**Comment by einfallstoll** [comment]
I'm not used to TypeScript, but I would love to help you out.
Would it be sufficient to create the file `lib/express-ntlm.d.ts` with the first snippet as its content? And the example should probably go into the README...

**Comment by Weber-D** [comment]
I've the same problem with JavaScript. Since I'm only using TypeScript, I don't have experience on providing Types for this. When writing TypeScript, you don't need any additional typings cause they're already there. 

But I think this should be enough for the request object to work. The important thing is that we're using `NtlmRequest` instead of the express one.

To make this full TS compatible, we need typings for the `ntlm` function call, too. At the moment this is a object of type `any`. So we can't be sure that important propertys like `domaincontroller` are present at compiling time.

**Comment by einfallstoll** [comment]
Could you try my test-branch and see if it works?

Something like this should work to install it:

````
npm install --save git+https://git@github.com/einfallstoll/express-html.git#typescript-bindings
````

**Comment by Weber-D** [comment]
Seems that we need some kind of modification here: VS Code looks for typings in the index file, so we need to move `express-ntlm/lib/express-ntlm.d.ts` one level up to `express-ntlm/index.d.ts`. Then it works, but only by manually importing `import { NtlmRequest } from "express-ntlm";`

The intellisense provided by VS Code (suggesting the import statement when using `NtlmRequest`) doesn't work. Couldn't find it out yet. I have the same problem on the first Typescript library I developed. Have to investigate this more deep when time is avaliable. 

For now we can use the file moving as workaround and do some documentation so that Typescript developers know they need those imports. 

Additionally, there are still no definitions for the middleware-function and it's options. I tried to fix this using

```ts
declare function ntlm(options: NtlmOptions): RequestHandlerParams;
export interface NtlmOptions {
  debug?: () => void;
  domain: string;
  domaincontroller: string;
}
```
without being able to use it cause of the following error: 

> app.use(express_ntlm_1.ntlm({
>                        ^
> TypeError: express_ntlm_1.ntlm is not a function

**Comment by awn70** [comment]
You can try this one, it's no perfect but it seems to work (`express-ntlm/index.d.ts`).
```typescript
import express = require( 'express' );
import tls = require( 'tls' );

declare var expressNtlm: expressNtlm.ntlm;
export = expressNtlm;

declare namespace expressNtlm {
    export interface NtlmInfo {
        DomainName: string,
        UserName: string,
        Workstation: string,
        push?: void
    }

    export interface NtlmRequest extends express.Request {
        ntlm?: NtlmInfo
    }

    export interface NtlmOptions {
        badrequest?: express.RequestHandler,
        forbidden?: express.RequestHandler,
        internalservererror?: express.RequestHandler,
        unauthorized?: express.RequestHandler,
        domain?: string,
        domaincontroller?: string | string[],
        tlsOptions?: tls.TlsOptions,
        debug?: Function,
        prefix?: string
    }

    export interface ntlm {
        ( options: NtlmOptions ): express.RequestHandler;
    }
}
```

**Comment by einfallstoll** [comment]
Can anyone approve whether the typings from @awn70 work? What about the issue of @Weber-D with the `express-ntlm/index.d.ts`?
