### ISSUE TITLE
Event "unauthorized" always triggering

### ISSUE THREAD

**Issue by grishnyakov** [einfallstoll/express-ntlm#72]
2.5.2

If i use "unauthorized" handler, this handler will been triggered in all situations. request.ntlm will not correct.
![image](https://user-images.githubusercontent.com/29563933/84632654-a7eabf00-af08-11ea-94e4-3bab812cd4e7.png)

But if i do not use this handler, request.ntlm is correct.
![image](https://user-images.githubusercontent.com/29563933/84633166-6c9cc000-af09-11ea-99c9-977ef736fc91.png)

**Comment by einfallstoll** [comment]
The `unauthorized` option is always triggered if the connections is not yet authenticated and it will set the appropriate response headers, in order to tell the browser to initiate an NTLM authentication like this:

```
function(request, response, next) {
    response.statusCode = 401;
    response.setHeader('WWW-Authenticate', 'NTLM');
    response.end();
}
```

You should not need to overwrite this option at all, except if you want to offer some alternative authentication methods (e.g. Basic Authentication).

If you don't set the response headers (like you did in your example), the browser will not authenticate and therefore `request.ntlm` will never be set, since there was no authentication. So what you describe is expected behaviour to me.

There's a common misunderstanding between `401 Unauthorized` and `403 Forbidden`, so maybe you don't want to log users that aren't yet authenticated (and are "unauthorized"), but you want to log user that failed to log in (and are "forbidden" to pass).

**Comment by grishnyakov** [comment]
Why this event is triggered when user is authenticated?

**Comment by einfallstoll** [comment]
This is probably a misconception about NTLM: Regular authentication protocols authenticate the user on a session-basis. NTLM being the shitty thing it is authenticates on a connection-basis. A browser nowadays uses multiple connections, therefore the user itself will be authenticated for every single connection.

This is stupid, but that's how it is.

Maybe you can learn a bit about this and how to abuse NTLM to authenticate a session in issue #69.
