### ISSUE TITLE
express-ntlm returning empty username

### ISSUE THREAD

**Issue by quietgecko** [einfallstoll/express-ntlm#74]
I'm using express-ntlm to get the current user's windows username. As a test I created this simple express server that prints the request object

var express = require('express'),     
ntlm = require('express-ntlm');  
var app = express();  
app.use(ntlm());  
app.all('*', function(request, response) {     
    response.end(JSON.stringify(request.ntlm)); 
});  
app.listen(8070);
In the response, I get the following on clicking this link http://localhost:8070/

{"UserName":"","Workstation":"LAPTOP-12345","Authenticated":true}

Why is the UserName empty? Is it due to some setting in the Browser? I tried using both chrome and internet explorer but get the same result. I was hoping to get the username, so that i can identity who the user is as this is for an angular intranet application and i dont want the user to enter any username/password and deal with that stuff

**Comment by einfallstoll** [comment]
Wild guess based on the missing `DomainController` option and the missing `DomainName` in the result: You're not in a corporate environment with an Active Directory, right?

Running `ntlm()` without providing a `DomainController` is discouraged, because it's just mocking an NTLM negotiation. It's basically the NTLM version of a dad joke: "Please authenticate" - "I'm confused" - "Hi, confused. I'm dad."

If you want to build a web application (e.g. on the internet for end users) without dealing with usernames and passwords, I recommend to use OAuth. People can authenticate against your application using an identity provider you specify, e.g. Google, Facebook, Microsoft, Apple, or any OpenID Connect compatible provider. Have a look at passport.js.

**Comment by quietgecko** [comment]
hello Fabio. Thanks for your response. 

I am in a small corporate env. It does have an AD. I had not provided the DomainController and DomainName  as i was just testing the  express-ntlm package

I tried using -[node-sspi](https://www.npmjs.com/package/node-sspi)  and it seems to identify  me as shown below:
Hello AzureAD\myemail@company.com! Your sid is S-XXXXXXXXXX  and you belong to following groups:
~
But  this package is not available in linux environment, and my express/angular app needs to be hosted on the linux environment . 
The users will use their laptops on the local intranet to access the angular app. It is not for the Internet
Hence express-ntlm suited my requirements as its available in a linux environment and could identify the logged in windows user when accessing this app from their browser
But i am not sure why the UserName is empty thought. It seems to identify the WorkStation correctly thought

Thank you

**Comment by einfallstoll** [comment]
Interesting! Could you try to set the `DomainController` options and see whether you get the correct results?

It could definitely be due to some settings (probably pushed via GPO). Also, I don't know about the influences of the AD being hosted on Azure, but I assume it should not make a difference.
