### ISSUE TITLE
NTLM & Reverse Proxy

### ISSUE THREAD

**Issue by yapnel** [einfallstoll/express-ntlm#76]
Hi,

Many thanks for developing and sharing this library.

I am trying to understand the problem why NTLM doesn't work with reverse proxy. Are you able to explain in depth on the technical side of things? 

I have run into this issue users getting mixed up and wondering if there is a way to overcome this limitation. 

I have tried

1) To do response.connection.destroy() after sending the output of the NTLM json and it seems to terminate the connection and prevent reusing again. However, in my load testing on concurrency, after a while I get connection reset and I suspect it is due to the destroy connection explicitly?

2) To set response.setHeader("Connection": "close") and that didn't make any difference either as the connection is still getting reused

Any help will be much appreciated

Thanks

Nelson

**Comment by einfallstoll** [comment]
Hi Nelson,

NTLM authenticates the connection _between_ the reverse proxy and the application layer. Usually reverse proxies reuse the connections for performance reasons the same way a browser would. If you explicitly destroy the connection, this could have some unintended side-effects and also requires every single connection to reauthenticate on creation, which will result in lots of traffic for every component including the domain controller.

The `Connection: close` might not be honored by the reverse proxy, depending on the configuration.

NTLM was not designed for this and I have no influence, since this is how it works unfortunately.

I know that nginx has some special NTLM configuration in its enterprise product, which will mitigate the issues mentioned above. I don't know the details, but I assume it will keep the connections on a per-user basis and avoids reusing them.

I'd suggest to not use a reverse proxy at all or configure the reverse proxy accordingly. Alternatively, you might be able to handle NTLM on the reverse proxy itself and pass the user to the application layer in a header or something.

Another option could be to run a small authentication application on a different port (bypassing the reverse proxy), authenticate the user and then establish a session using a cookie (which is not port-isolated). Session information would have to be stored in a shared session storage (e.g. redis, memcache) which would be accessible from both the authentication application and your regular web application.
